spring.config.import=optional:file:src/main/resources/secret/.env[.properties]
spring.application.name=codesight

server.port=8081

spring.datasource.url=${DB_URL}

spring.datasource.username=${DB-USERNAME}
spring.datasource.password=${DB-PASSWORD}

app.jwt.secret=${JWT-SECRET}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1

app.frontend.url = http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL-USERNAME}
spring.mail.password=${MAIL-PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

